#!/bin/bash
set -eux

echo -e '[rdo]\nname=RDO\nbaseurl=https://repos.fedorapeople.org/repos/openstack/openstack-icehouse/epel-7/\nenabled=1\ngpgcheck=0' > /etc/yum.repos.d/rdotmp.repo

install-packages -m openvswitch openvswitch-switch_package

rm -f /etc/yum.repos.d/rdotmp.repo

if [ "$DIB_INIT_SYSTEM" == "systemd" ] ; then
    os-svc-enable -n openvswitch-switch
fi

if [ "$DIB_INIT_SYSTEM" == "upstart" ] ; then
    echo "start on starting cloud-init-nonet" >> /etc/init/openvswitch-switch.override
    if [ ! -f /etc/init/openvswitch-switch.conf ] ; then
        cat << 'EOF' > /etc/init/openvswitch-switch.conf
# openvswitch-switch
# the purpose of this job is
#  * start openvwitch-switch in upstart rather than SysV startup
pre-start script
      export RUNLEVEL=2
      /etc/init.d/openvswitch-switch start
end script
post-stop exec /etc/init.d/openvswitch-switch stop
EOF
    fi
fi
